# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(
    ['know.py'],
    pathex=['.'],
    binaries=[],
    datas=[('src/assets', 'src/assets')],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'sqlite3',
        'src.app.routers.file',
        'src.app.routers.files',
        'src.app.routers.rag',
        'src.app.routers.retrieval_ops',
        'src.app.routers.datasets',
        'src.app.routers.chat',
        'src.app.routers.tags',
        'src.app.routers.search',
        'src.app.routers.workflows',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='uroboros_engine',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
