<!-- IBM Cúram Express Rules (CER) Document Type Definition -->
<!ELEMENT RuleSet (Class*)>
<!ATTLIST RuleSet
    name CDATA #REQUIRED
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

<!ELEMENT Class (Annotations?, Attribute*)>
<!ATTLIST Class
    name CDATA #REQUIRED
    extends CDATA #IMPLIED
    isAbstract (true|false) "false">

<!ELEMENT Attribute (Annotations?, (type | calculation))>
<!ATTLIST Attribute
    name CDATA #REQUIRED>

<!ELEMENT calculation ANY>
<!ELEMENT compare ANY>
<!ATTLIST compare
    comparison CDATA #REQUIRED>

<!ELEMENT condition ANY>
<!ELEMENT choose ANY>
<!ELEMENT timeline ANY>
